### ISSUE TITLE
Issue in Import geonames for united kingdom

### ISSUE THREAD

**Issue by Mohit-saini-dotsquares** [AdobeDocs/commerce-admin.en#28]
Issue in ./help/stores-purchase/shipping-in-store-delivery.md

bin/magento inventory-geonames:import UK
Error:-Importing UK: Cannot download country
Expected result: Importing UK: OK

**Comment by hguthrie** [comment]
It looks like you are having a problem with running a `bin/magento` CLI command.
Is there an issue with the documentation? Can you be more specific?

**Comment by keharper** [comment]
@Mohit-saini-dotsquares The example posted [here](https://experienceleague.adobe.com/docs/commerce-admin/inventory/cli.html?lang=en#import-geocodes) shows lowercase country codes.

If specifying `uk` instead of `UK` doesn't work, then you either have a configuration error, or you've found a bug. In those cases, it's not a doc bug, and we can't help further.

If it does work, you can help us improve the documentation by updating the description of this PR to state that the country codes must be in lowercase. If you think it would be helpful to cross link the page you originally referenced and the page I referenced, let us know that as well.

**Comment by hguthrie** [comment]
Closing this issue due to lack of response. If you continue to experience this issue, you can reopen and include additional information to help us improve the documentation. Thanks!
