### ISSUE TITLE
Note that support for Braintree Local Payment Methods is incomplete

### ISSUE THREAD

**Issue by Crissov** [AdobeDocs/commerce-admin.en#31]
Issue in ./help/configuration-reference/sales/braintree.md 
https://experienceleague.adobe.com/docs/commerce-admin/config/sales/payment-methods/braintree.html#local-payment-methods

![image](https://github.com/AdobeDocs/commerce-admin.en/assets/6200185/47f5fe31-e1ac-453e-94ad-30ab54a4e607)

Compare with https://developer.paypal.com/braintree/docs/guides/local-payment-methods/overview
All _non-instant_ plocal payment methods are missing and two more: Polish BLIK and German _Pay upon Invoice_.
Furthermore, Direct Debit is not mentioned in the Braintree documentation as a local payment method.

Commerce Implementation | Braintree Local Payment Method | Customer country
-- | -- | --
❌ | BLIK | 🇵🇱Poland
✅ | Bancontact | 🇧🇪Belgium
❌ | Boleto Bancário (non-instant) | 🇧🇷Brazil
✅ | EPS | 🇦🇹Austria
✅ | Giropay | 🇩🇪Germany
✅ | iDEAL | 🇳🇱Netherlands
✅ | Klarna Pay Now / SOFORT | 🇦🇹Austria, 🇧🇪Belgium, 🇩🇪Germany, 🇳🇱 Netherlands, 🇪🇸Spain, 🇬🇧United Kingdom
❌ | Multibanco (non-instant) | 🇵🇹Portugal
✅ | MyBank | 🇮🇹Italy
❌ | OXXO (non-instant) | 🇲🇽Mexico
❌ | Pay Upon Invoice | 🇩🇪Germany
✅ | P24 | 🇵🇱Poland
✳️ | SEPA/ELV Direct Debit | 🇪🇺(not mentioned in Braintree documentation)

There should be a note to this effect! 

Please also do not hesitate to reference Github issues for the implementation of the missing options.

PS: It is unclear to me who is responsible for the Braintree module and its documentation. Braintree support says it’s Adobe.

**Comment by kartikmaniyar** [comment]
@Crissov Thank you for reporting this!
- But It's not an issue. We don't support all the local payment methods that you have found in Braintree Documentation(https://developer.paypal.com/braintree/docs/guides/local-payment-methods/overview) in our extension.
- We only support methods that you can find in the screenshot of Adobe Documentation(https://experienceleague.adobe.com/docs/commerce-admin/config/sales/payment-methods/braintree.html#local-payment-methods).
- Regarding **SEPA/ELV Direct Debit**, it was supported by Braintree earlier that's why it's there.
- For Non-instant, Our Braintree integration only supports instant local payment methods but not all at the moment.
- We will try to implement other instant local payment methods in the next release either 2.4.7-beta2 or 2.4.7 that we are not supporting at this time.

**Comment by Crissov** [comment]
I’m just asking for a Note in the documentation, so the investigating reader does not need to assume anything about the missing payment methods there.

**Comment by dobooth** [comment]
@leslietilling Do we have a PR around this?

**Comment by leslietilling** [comment]
@dobooth  Not yet...  should have that soon now that June release is out.

**Comment by leslietilling** [comment]
Resolved: https://github.com/AdobeDocs/commerce-admin.en/commit/3b80cf283db77e3c9193dc26d1de36f539c99093
